getOne:
   path: /posts/{!id}
   controller: App\Controller\PostController::getOne
   methods: GET
   requirements:
      id: '\d+'

getAll:
   path: /posts
   controller: App\Controller\PostController::getAll
   methods: GET
